export * from './areaController.service';
import { AreaControllerService } from './areaController.service';
export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './especialidadController.service';
import { EspecialidadControllerService } from './especialidadController.service';
export * from './estadoOtController.service';
import { EstadoOtControllerService } from './estadoOtController.service';
export * from './healthController.service';
import { HealthControllerService } from './healthController.service';
export * from './ordenTrabajoController.service';
import { OrdenTrabajoControllerService } from './ordenTrabajoController.service';
export * from './prioridadController.service';
import { PrioridadControllerService } from './prioridadController.service';
export * from './rolController.service';
import { RolControllerService } from './rolController.service';
export * from './ubicacionController.service';
import { UbicacionControllerService } from './ubicacionController.service';
export * from './usuarioController.service';
import { UsuarioControllerService } from './usuarioController.service';
export const APIS = [AreaControllerService, AuthControllerService, EspecialidadControllerService, EstadoOtControllerService, HealthControllerService, OrdenTrabajoControllerService, PrioridadControllerService, RolControllerService, UbicacionControllerService, UsuarioControllerService];
