/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrdenTrabajo { 
    id?: number;
    codigoOt: string;
    titulo: string;
    descripcion: string;
    fechaActualizacion?: string;
    fechaApertura?: string;
    fechaCierre?: string;
    fechaCompromiso?: string;
    idEspecialidad: number;
    idEstado: number;
    idPrioridad: number;
    idUbicacion: number;
    idUsuarioAsignado?: number;
    idUsuarioCreador: number;
}

