/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsuarioResponseDto { 
    id?: number;
    idRol?: number;
    nombreRol?: string;
    nombreCompleto?: string;
    correo?: string;
    activo?: boolean;
    fechaCreacion?: string;
}

